### ISSUE TITLE
Can't run with adopt-openjdk-1.8

### ISSUE THREAD

**Issue by baofeidyz** [zimujiang/TinyClip#1]
**adopt-openjdk-1.8** dosen't support the **jfxrt.jar** which the `javafx.application.Application` class in.

Please rewrite the **README.md** about **jdk1.8+** description, shoule be **Oracle JDK 1.8+** or note the **jfxrt.jar** where download and install.

**Comment by zimujiang** [comment]
已添加相关说明，3Q~
